In [22]:
import numpy as np
a=np.random.randn(3,3)
a=np.eye(3)
b=np.random.randn(3,1)
print(a)
print(b)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.08884564]
 [-0.34841228]
 [ 0.45947617]]


In [24]:
a=[[9.18, 0,2.04],[0,5.24,-2.04],[1,-1,-1]]
b=[[12],[9],[0]]

In [25]:
x=np.linalg.solve(a,b)
x.shape
x

array([[ 1.36377709],
       [ 1.61842105],
       [-0.25464396]])